### PR TITLE
add local ip address parameter fix #166

### LINKED ISSUE #166: php-debug listen only on ivp6 ip address but not on ipv4
hi
after i add php-debug to atom on my linux and i wanna test it so run:
```
# netstat -anp|grep 9000
tcp6       0      0 :::9000                 :::*                    LISTEN      5718/electron --typ
```
and i see that atom only listen on ipv6 ip address but not ipv4. how can i assign ipv4 or eg 127.0.0.1 as an ip to listen on?

### PR DESCRIPTION
**Pull request by lfarkas**
with this patch one can avoid to listen on ipv6 address while xdebug try to connect to ipv4 address.

### CODE REVIEW

**Comment by benbeadle** [comment]
I'm running Xdebug inside a docker container, and it won't connect to php-debug because it's only running on ipv6 - which this PR should solve.

**Comment by Multiply** [comment]
@cchamplin Any progress on getting this merged?

**Comment by BrizzleRocker** [comment]
@cchamplin I appreciate you're very busy but this is a bit of a show stopper for Docker users currently. Any chance of picking this up again please?

**Comment by cchamplin** [comment]
Since this patch has merge conflicts I cannot merge it directly, I've added the changes @lfarkas has in the pull request, these should be available in the next release.

**Pull request closed without merging**
